<a href="https://colab.research.google.com/github/lmeenakshi183/Deep-Learning-Elective/blob/main/DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math

## **Hebb Rule**

*For logic gates:*

In [ ]:
def hebbrule():   
  x1=[1,-1]
  x2=[1,-1]
  (w1,w2,w0)=(0,0,0)
  for i in range(0,2):
    for j in range(0,2):
      if (x1[i]==1 or x2[j]==1): #or gate
        y=1
      else:
        y=-1
      w1+=x1[i]*y
      w2+=x2[j]*y
      w0+=y
  print('Final weights are',w1,w2,w0)



In [ ]:
hebbrule()

Final weights are 2 2 2


*For recognition of 4 letters (with 9 neurons):*

In [ ]:

def alphhebb():   
  w1=[0,0,0,0,0,0,0,0,0]
  w2=[0,0,0,0,0,0,0,0,0]
  print('enter first letter')
  alph1=list(map(int,input().strip().split(',')))[:9]
  print('enter second letter')
  alph2=list(map(int,input().strip().split(',')))[:9]
  print('enter third letter')
  alph3=list(map(int,input().strip().split(',')))[:9]
  print('enter fourth letter')
  alph4=list(map(int,input().strip().split(',')))[:9]
  for m in range(0,9):
        w1[m]+=alph1[m]*1
        w2[m]+=alph1[m]*1
  for m in range(0,9):
        w1[m]+=alph2[m]*1
        w2[m]+=alph2[m]*-1
  for m in range(0,9):
        w1[m]+=alph3[m]*-1
        w2[m]+=alph3[m]*1
  for m in range(0,9):
        w1[m]+=alph4[m]*-1
        w2[m]+=alph4[m]*-1
  print('final weights are-')
  print(w1)
  print(w2)
  
  

      
    

In [ ]:
alphhebb()

enter first letter
1,1,1,1,1,-1,1,1,1
enter second letter
1,-1,1,-1,1,-1,1,-1,1
enter third letter
1,-1,-1,1,1,1,1,1,1
enter fourth letter
1,-1,1,1,1,1,1,-1,1
final weights are-
[0, 2, 2, -2, 0, -4, 0, 0, 0]
[0, 2, -2, 2, 0, 0, 0, 4, 0]


In [ ]:
# to give a test input, add the following code at the end
  print('')
  print('enter test letter')
  testletter=list(map(int,input().strip().split(',')))[:9]
  for m in range(0,9):
    yin1+=testletter[m]*w1[m]
    yin2+=testletter[m]*w2[m]
  if (yin1>0):
    y1=1
  else:
    y1=-1
  if (yin2>0):
    y2=1
  else:
    y2=-1
  print(y1,y2)

*For any number of inputs or neurons:*

In [ ]:
def hebbrulegen():
  n=int(input('enter the number of inputs:'))
  nrn=int(input('enter the number of input neurons:'))
  alph=np.empty(nrn,dtype=int)
  for i in range(0,n):
    alph=np.vstack([alph,list(map(int,input().strip().split(',')))[:nrn]])
  alph=np.delete(alph,0,axis=0)
  i=0
  while(i<n):
    if not (n>2**i and n<=2**(i+1)):
      i=i+1
    else:
      m=i+1
      break
  y=createy(m)
  y=y[:n,:]
  w=np.dot(y.T,alph)
  print('final weights are: ')
  print(w)

In [ ]:
def createy(x):
  no=2**x
  a=np.zeros(shape=[no,x],dtype=int)
  for i in range(0,no):
    binary=bin(no-i-1).replace("0b","").zfill(x)
    for j in range(x,0,-1):
      a[i,j-1]=int(binary[j-1])
  a=np.where(a==0,-1,a)
  return a

In [ ]:
hebbrulegen()

enter the number of inputs:4
enter the number of input neurons:9
1,1,1,1,1,-1,1,1,1
1,-1,1,-1,1,-1,1,-1,1
1,-1,-1,1,1,1,1,1,1
1,-1,1,1,1,1,1,-1,1
final weights are: 
[[ 0  2  2 -2  0 -4  0  0  0]
 [ 0  2 -2  2  0  0  0  4  0]]


## **Backpropagation**

*Specific to question solved in MATLAB:*

In [ ]:
def backprop():
  #initialization
  w=np.array([-1,1,2])
  w0=np.array([-1])
  v=np.array([[2,1,0], [1,2,2],[0,2,1]])
  v0=np.array([0,0,-1])
  x=np.array([0.6,0.8,0])
  t=0.9
  alpha=0.3
  z=np.empty(3)
  delt=np.empty(3)
  #feed forward
  count=1
  epoch=0
  while count is 1:
    error=0
    zin=np.add(np.dot(v.T,x.T),v0.T)
    for i in range (0,3):
      z[i]=1/(1+math.exp(-1*zin[i]))
    yin=np.add(np.dot(w,z.T),w0)
    y=1/(1+math.exp(-1*yin))
  #backpropagation of error
    sdel=(t-y)*y*(1-y)
    delin=np.dot(sdel,w)
    for i in range (0,3):
      delt[i]=delin[i]*z[i]*(1-z[i])
  #updating weights and bias
    delv=alpha*np.dot(x.T,delt)
    delv0=alpha*delt
    v=v+delv
    v0=v0+delv0
    delw=alpha*np.dot(sdel,z)
    delw0=alpha*sdel
    w=np.add(w,delw)
    w0=np.add(w0,delw0)
    error=error+(t-y)**2
    if error<0.005:
      count=0
    else:
      epoch=epoch+1
  print(epoch)
  print(v)
  print(error)
  print(w)

In [ ]:
backprop()

45
[[2.01141792 1.01141792 0.01141792]
 [1.01141792 2.01141792 2.01141792]
 [0.01141792 2.01141792 1.01141792]]
0.004951783877426604
[-0.65767181  1.35123096  2.25948904]
